/*
 * This file was generated by the Gradle 'init' task.
 */
description = "MapManager-Core"

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm") version "2.3.0"
    id("com.gradleup.shadow") version "8.3.6"
}

group = "work.alsace.mapmanager"
version = "3.4.1"


dependencies {
    implementation(project(":MapManager-API"))

    implementation("net.kyori:adventure-api:4.14.0")
    implementation("org.apache.logging.log4j:log4j-core:2.17.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.2")
    implementation("com.github.Querz:NBT:6.1")

    compileOnly("org.mvplugins.multiverse.core:multiverse-core:5.7.2")
    compileOnly("net.luckperms:api:5.3")
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")
}

tasks.shadowJar {
    archiveFileName.set("${project.name}-${project.version}.jar")
    from(sourceSets.main.get().output)

    mergeServiceFiles {
        include("META-INF/services/*")
    }

    configurations = listOf(project.configurations.runtimeClasspath.get())
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}
