name: MapManager-Core
main: work.alsace.mapmanager.MapManagerImpl
version: 3.2.0
depend:
  - LuckPerms
  - Multiverse-Core
softdepend:
  - VoidGen
api-version: '1.16'
authors:
  - AlsaceWork
  - CHuNan
  - Hanamizu
commands:
  import:
    usage: /import
    description: import a world map
  world:
    usage: /world
    description: modify world settings
  write:
    usage: /write
    description: none
  delete:
    usage: /delete [world]
    description: delete a world map.
  mapadmin:
    usage: /mapadmin.md <operation>
    description: none.
  worldtp:
    aliases: [ wtp ]
    usage: /worldtp <world name>
    description: Teleport you to a specific world.
  create:
    usage: /create
    description: Create a new flat world without buildings.
