name: Package and Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: List build artifacts for Core
        run: ls -lah ./MapManager-Core/build/libs/

      - name: Upload Core Artifact to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./MapManager-Core/build/libs/MapManager-Core-${{ github.event.release.tag_name }}.jar
          # Assuming the tag name is used as the version. Adjust if necessary.
          asset_name: MapManager-Core-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive

      - name: List build artifacts for API
        run: ls -lah ./MapManager-API/build/libs/

      - name: Upload API Artifact to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./MapManager-API/build/libs/MapManager-API-${{ github.event.release.tag_name }}.jar
          # Adjust the asset_path if your Gradle project configuration produces a different jar name
          asset_name: MapManager-API-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
